universe/qemu: generate and package binfmt conf for user mode emulators
[ commit b0917a82e76da228cdafaa1b1c3bfece6bae542f ]

diff --git a/universe/qemu/APKBUILD b/universe/qemu/APKBUILD
--- a/universe/qemu/APKBUILD
+++ b/universe/qemu/APKBUILD
@@ -1,6 +1,6 @@
 pkgname=qemu
 pkgver=10.2.0
-pkgrel=0
+pkgrel=1
 pkgdesc="QEMU is a generic machine emulator and virtualizer"
 url="https://qemu.org/"
 arch="all"
@@ -431,6 +431,14 @@ package() {
 	cd "$builddir"/build
 	make DESTDIR="$pkgdir" install
 
+	mkdir -p "$pkgdir"/usr/lib/binfmt.d
+	"$builddir"/scripts/qemu-binfmt-conf.sh \
+		--systemd ALL \
+		--exportdir "$pkgdir"/usr/lib/binfmt.d \
+		--qemu-path /usr/bin \
+		--persistent yes \
+		--preserve-argv0 yes
+
 	install -Dm640 -g qemu "$srcdir"/bridge.conf \
 		"$pkgdir"/etc/qemu/bridge.conf
 
@@ -460,6 +468,9 @@ _subsys() {
 	esac
 
 	amove usr/bin/qemu-$name
+	# Don't fail if the conf doesn't exist (e.g. because it's a system emulator, or
+	# the name/arch doesn't have conf for the pkg arch)
+	amove usr/lib/binfmt.d/qemu-$name.conf || true
 
 	local _arch=${name#system-}
 	case "$name" in
