universe/glslang: update to 11.12.0-r0
[ Alpine commit 66a87717f8a8a51bc9724ab852a243ed885df9dd ]

diff --git a/universe/glslang/APKBUILD b/universe/glslang/APKBUILD
--- a/universe/glslang/APKBUILD
+++ b/universe/glslang/APKBUILD
@@ -1,5 +1,5 @@
 pkgname=glslang
-pkgver=11.6.0
+pkgver=11.12.0
 pkgrel=0
 pkgdesc="Khronos reference front-end for GLSL, ESSL, and sample SPIR-V generator"
 url="https://github.com/KhronosGroup/glslang"
@@ -7,58 +7,53 @@ arch="all"
 license="BSD-3-Clause"
 depends_dev="$pkgname"
 makedepends="cmake samurai python3 bison spirv-tools-dev"
-checkdepends="bash"
-subpackages="$pkgname-static $pkgname-dev"
-source="$pkgname-$pkgver.tar.gz::https://github.com/KhronosGroup/glslang/archive/$pkgver.tar.gz
-	"
+checkdepends="bash gtest-dev"
+subpackages="$pkgname-static $pkgname-libs $pkgname-dev"
+source="$pkgname-$pkgver.tar.gz::https://github.com/KhronosGroup/glslang/archive/refs/tags/$pkgver.tar.gz"
+
+case "$CARCH" in
+s390x) options="$options !check" ;; # testsuite seems to fail on big endian
+esac
 
 build() {
 	if [ "$CBUILD" != "$CHOST" ]; then
 		CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
 	fi
-	mkdir -p build-shared build-static
-	(cd build-shared
-		cmake \
-			-GNinja \
-			-DCMAKE_INSTALL_PREFIX=/usr \
-			-DCMAKE_INSTALL_LIBDIR=lib \
-			-DCMAKE_BUILD_TYPE=None \
-			-DCMAKE_CXX_FLAGS="$CXXFLAGS" \
-			-DBUILD_SHARED_LIBS=ON \
-			$CMAKE_CROSSOPTS ..
-		ninja
-	)
+	cmake -B build-shared -G Ninja \
+		-DCMAKE_INSTALL_PREFIX=/usr \
+		-DCMAKE_INSTALL_LIBDIR=lib \
+		-DCMAKE_BUILD_TYPE=MinSizeRel \
+		-DBUILD_SHARED_LIBS=ON \
+		-DENABLE_CTEST="$(want_check && echo ON || echo OFF)" \
+		$CMAKE_CROSSOPTS
+	cmake --build build-shared
+
 	sed -i '/add_library(glslang-default-resource-limits/ s/$/ STATIC/' StandAlone/CMakeLists.txt
-	(cd build-static
-		cmake \
-			-GNinja \
-			-DCMAKE_INSTALL_PREFIX=/usr \
-			-DCMAKE_INSTALL_LIBDIR=lib \
-			-DCMAKE_BUILD_TYPE=None \
-			-DCMAKE_CXX_FLAGS="$CXXFLAGS" \
-			-DCMAKE_C_FLAGS="$CFLAGS" \
-			-DBUILD_SHARED_LIBS=OFF \
-			$CMAKE_CROSSOPTS ..
-		ninja
-	)
+	cmake -B build-static -G Ninja \
+		-DCMAKE_INSTALL_PREFIX=/usr \
+		-DCMAKE_INSTALL_LIBDIR=lib \
+		-DCMAKE_BUILD_TYPE=MinSizeRel \
+		-DBUILD_SHARED_LIBS=OFF \
+		-DENABLE_CTEST="$(want_check && echo ON || echo OFF)" \
+		$CMAKE_CROSSOPTS
+	cmake --build build-static
 }
 
 check() {
-	case "$CARCH" in
-		s390x|mips64) return 0;; # testsuite seems to fail on big endian
-	esac
-	cd Test
 	msg "Testing shared version of glslang"
-	./runtests localResults ../build-shared/StandAlone/glslangValidator ../build-shared/StandAlone/spirv-remap
+	ctest --test-dir build-shared --output-on-failure
+
 	msg "Testing static version of glslang"
-	./runtests localResults ../build-static/StandAlone/glslangValidator ../build-static/StandAlone/spirv-remap
+	ctest --test-dir build-static --output-on-failure
 }
 
 package() {
-	DESTDIR="$pkgdir" ninja -C build-shared install
-	DESTDIR="$pkgdir" ninja -C build-static install
+	# installing static first lets shared overwrite the executables so they
+	# themselves are not statically linking the library
+	DESTDIR="$pkgdir" cmake --install build-static
+	DESTDIR="$pkgdir" cmake --install build-shared
 }
 
 sha512sums="
-f7c1affdb4923758f9ff5cae894c40ca86e723850a6265d9c13f996311451bd84c70a178d8d6c0961dcee39c19d724f02d19a21ee6f67f1bb4cdbc618fdc12cf  glslang-11.6.0.tar.gz
+fd955f9912551668056dfe52835eef11e5dc0bf0d25b2d961a31f684adbd63bc6380759944c1921cfd63d359a58c7cc3a4a4d5eea69fa1b050f58960e5101271  glslang-11.12.0.tar.gz
 "
