universe/abuild: support multiple entries in sign_verify

diff --git a/universe/abuild/0110-add-a-new-step-to-sign-files-with-sign_impl-command.patch b/universe/abuild/0110-add-a-new-step-to-sign-files-with-sign_impl-command.patch
--- a/universe/abuild/0110-add-a-new-step-to-sign-files-with-sign_impl-command.patch
+++ b/universe/abuild/0110-add-a-new-step-to-sign-files-with-sign_impl-command.patch
@@ -1,4 +1,4 @@
-From 13b7e60671399069b824c33585f2f367b11109f6 Mon Sep 17 00:00:00 2001
+From d1097f8481a833ccbde8fe7c54fb7745c42b12f1 Mon Sep 17 00:00:00 2001
 From: Alexey Kodanev <aleksei.kodanev@bell-sw.com>
 Date: Fri, 11 Nov 2022 19:16:23 +0300
 Subject: [PATCH] add a new step to sign files with sign_impl command
@@ -10,17 +10,17 @@ and sign_verify in APKBUILD files.
  1 file changed, 23 insertions(+)
 
 diff --git a/abuild.in b/abuild.in
-index db44753..81442c2 100644
+index 3885e20..400cf8a 100644
 --- a/abuild.in
 +++ b/abuild.in
-@@ -811,6 +811,28 @@ build() {
+@@ -801,6 +801,28 @@ build() {
  	:
  }
  
 +sign() {
 +	[ -z "$sign_list" ] && return 0
 +
-+	if ! type -q 'sign_impl'; then
++	if ! command -v 'sign_impl' >/dev/null; then
 +		warning "Please provide 'sign_impl' command/function to sign 'sign_list' (or sign manually)"
 +		return 0
 +	fi
@@ -29,20 +29,20 @@ index db44753..81442c2 100644
 +	local f
 +	local cert=""
 +
-+	if [ "$sign_verify" ]; then
-+		cert="$srcdir/$sign_verify"
-+		[ -f "$cert" ] || die "Failed to find sign_verify file: $cert"
-+	fi
-+
 +	for f in $sign_list; do
-+		sign_impl "$dir"/$f "$cert"
++		local c; for c in $sign_verify; do
++			cert="$srcdir/$c"
++			[ -f "$cert" ] || die "Failed to find sign_verify file: $cert"
++
++			sign_impl "$dir"/$f "$cert"
++		done
 +	done
 +}
 +
  # generate a simple tar.gz package of pkgdir
  targz() {
  	cd "$pkgdir" || return 1
-@@ -1503,6 +1525,7 @@ prepare_package() {
+@@ -1509,6 +1531,7 @@ prepare_package() {
  	[ ! -d "${subpkgdir:-$pkgdir}" ] && die "Missing ${subpkgname:+sub}pkgdir for ${subpkgname:-$pkgname}"
  	msg "Preparing ${subpkgname:+sub}package ${subpkgname:-$pkgname}..."
  	stripbin
@@ -51,5 +51,5 @@ index db44753..81442c2 100644
  	prepare_trace_rpaths
  	prepare_symlinks
 -- 
-2.52.0
+2.34.1
 
